import RootNavigation from "@/components/ui/RootNavigation/RootNavigation";
import { RootNavigationItemProps } from "@/components/ui/RootNavigation/RootNavigation.types";
import { podkova, sora } from "@/lib/fonts";
import dayjs from "dayjs";
import "dayjs/locale/nl";
import customParseFormat from "dayjs/plugin/customParseFormat";
import isBetween from "dayjs/plugin/isBetween";
import type { Metadata } from "next";
import { FC, PropsWithChildren } from "react";
import "./globals.css";

dayjs.locale("nl");

dayjs.extend(customParseFormat);
dayjs.extend(isBetween);

export const metadata: Metadata = {
  title: "Haegepoorters",
  description: "Generated by create next app"
};

const MENU_START = [
  { name: "Startpagina", href: "/", icon: "home-5-line" },
  { name: "Haegeprekerke", href: "/haegeprekerke", icon: "book-3-line" },
  { name: "Nieuws & blog", href: "/blog", icon: "newspaper-line" },
  { name: "Leiding", href: "/leiding", icon: "team-line" },

  { name: "HP Rénove", href: "/vzw", icon: "hammer-line" },
  { name: "Contact", href: "/contact", icon: "chat-4-line" }
] satisfies RootNavigationItemProps[];

const MENU_END = [
  { name: "Digitale lidkaart", href: "/ga/lidkaart", icon: "qr-code-line" }
] satisfies RootNavigationItemProps[];

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html
      lang="nl"
      className={`${sora.variable} ${podkova.variable} h-full antialiased [interpolate-size:allow-keywords]`}
    >
      <body className="min-h-full flex flex-col h-full pl-(--rootnavigation-size-min)">
        <RootNavigation
          itemsStart={MENU_START}
          itemsEnd={MENU_END}
          className=" "
        />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
